server:
  tomcat:
    max-swallow-size: -1
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
  port: 7050
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  cloud:
    sentinel:
      transport:
        dashboard: sentinel:8858 # 指定控制台服务的地址
    loadbalancer:
      retry:
        enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.233:3306/rongan?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 123.com
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  #redis 配置
  redis:
    database: 10
    host: 192.168.0.233
#    cluster:
#      nodes: 192.168.0.168:6380,192.168.0.168:6381,192.168.0.168:6382
    password: 123.com
    port: 6379
    lettuce:
      pool:
        max-active: 0   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 0    #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
#rongan:
#  lock:
#    redisson:
#      address: ${spring.redis.host}:${spring.redis.port}
#      password: ${spring.redis.password}
#      type: STANDALONE
#      enabled: true
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/rongan/**/mapper/xml/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
  configuration:
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true


rongan-ssl:
  ca: /usr/share/nginx/ssl/root.p12
  ca-pass: 123.com #ca-key
  client: /usr/share/nginx/ssl/client.p12
  client-pass: 123.com #client-key

feign:
  #  sentinel:
  #    enabled: true
  client:
    config:
      default:
        connectTimeout: 1800000
        readTimeout: 1800000

rongan-api:
  fateflow-url: http://192.168.0.233:9380
  fateflow-federation-url: http://192.168.0.233:8059

ribbon:
  eager-load:
    enabled: true
    clients: pir-c-stream
