spring:
#  profiles:
#    active: usage_message
  rabbitmq:
    host: 192.168.56.103
    port: 5672
    username: guest
    password: guest
#logging:

#client:
logging:
  config: classpath:log4j2.xml
  level:
    org: ERROR
#  duration: 30000